### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by vitaly-t** [npm/download-counts#21]
Any idea why it stopped working 2 days ago?

Today is March 12, and I can only get statistics for March 9 now, is when it stopped working.

API i'm testing: https://api.npmjs.org/downloads/point/last-day/pg-promise

**Comment by seldo** [comment]
The batch job underlying the downloads API has broken and a replacement is being put together ASAP.

**Comment by vitaly-t** [comment]
How's that coming? :)

Still not working... :(

**Comment by analog-nico** [comment]
+1 Looking forward to the fix. Thanks!

**Comment by jonhester** [comment]
@seldo Any eta on this?

**Comment by seldo** [comment]
Today or tomorrow.

**Comment by jonhester** [comment]
Awesome, thanks for the update.

**Comment by seldo** [comment]
Fixed! Download counts are back (with the exception of 2015-03-11, for which there is a mysterious data error I am still debugging)

**Comment by jonhester** [comment]
@seldo Thanks!

**Comment by analog-nico** [comment]
Did the API change?

For example the following request:
`https://api.npmjs.org/downloads/range/2015-03-09:2015-03-19/request-promise`

returns:
`{"downloads":[{"day":"2015-03-09","downloads":660}],"start":"2015-03-09","end":"2015-03-19","package":"request-promise"}`

**Comment by analog-nico** [comment]
Oh, I see. The API indeed changed. This request with the range only up to yesterday works:
`https://api.npmjs.org/downloads/range/2015-03-09:2015-03-18/request-promise`

The API didn't digest the current day. I the GMT timezone it is the day 2015-03-19.

@seldo can you please clarify at what point in time the current date becomes valid and can be requested?

**Comment by seldo** [comment]
Stats are calculated once daily for the previous day, at least for the moment. I put more detail into the README of the branch that got pushed today: https://github.com/npm/download-counts/blob/ljv-emr-counts/README.md#data-source

(it's still being code-reviewed and will probably become master tomorrow)

**Comment by analog-nico** [comment]
@seldo that makes totally sense. But since the old version didn't have a problem with that now the new version might have a flaw.

Apart from the case I mentioned above I am wondering about the following case: Usually, the new data for the previous day came in between 12:30 and 1:30 GMT after midnight. Let us say it is 12:30 GMT and it is a day in which the numbers come in at 1:30. It is valid to ask the API to give the data for the previous day since it is past midnight. But how will the API respond then since the data is not available yet? The problem I have is that both requests I pasted in my previous comments give a perfectly valid response. Only because I knew that the package request-promise has plenty of downloads each day I spotting the incorrect response.

I know my request with the range until 2015-03-19 makes no sense. But the responses indicate that the API is flaky. I definitely appreciate if you could pay special attention to the edge cases when reviewing the code changes. Thank you very much! And if I can help somehow let me know.

**Comment by analog-nico** [comment]
FYI: Now at 2:53am UTC a range up to 2015-03-19 works as previously.

**Comment by seldo** [comment]
@analog-nico: the stats API is very heavily cached, so I think you were probably just seeing a caching artifact.

**Comment by analog-nico** [comment]
@seldo Oh, I didn't think of that. Funny it coincided with my tests like this. :D Thank you very much!

**Comment by vitaly-t** [comment]
It doesn't seem to work still. For example, on my project page, it shows the same number for the last 4 days, without any update: https://www.npmjs.com/package/pg-promise

**Comment by analog-nico** [comment]
@seldo I tested the behavior by calling the API repeatedly between 23:59 UTC and about 1:15 UTC and it worked as expected. Thanks for the fix!

**Comment by analog-nico** [comment]
@vitaly-t If I request the data of the last 30 days (range query) I get this:

![screen shot 2015-03-20 at 11 20 45](https://cloud.githubusercontent.com/assets/1407390/6754590/ec38210c-cef3-11e4-935b-a548c2cc36b3.png)

The last four days in reverse order are: 21, 21, 39, 16.

Which command did you use to retrieve the data?

**Comment by vitaly-t** [comment]
@analog-nico 
I just would open the webpage, did Ctrl+F5 to reset cache, no change, showing 21 downloads for the last 4 days.

**Comment by analog-nico** [comment]
@vitaly-t The webpage has the weird behavior that it shows the last number available. E.g. if yesterday the lib got zero downloads and the day before it got 21 it is still showing that 21 - not 0. During the outage of the API all pages showed the last number available (from 2015-03-09). In your case it should have been 673. And since the fix is in place since two days you should have seen 673, 673, 21, 21.

Anyway, I am just a user so maybe @seldo has better insight into this.
