### ISSUE TITLE
Download count stopped working

### ISSUE THREAD

**Issue by christian-bromann** [npm/download-counts#45]
For 5 days there hasn't been any updates to the download count. What is broken?

**Comment by joeledwards** [comment]
Thank you for bringing this to our attention, Christian. We have corrected the underlying issue and back-filled the missing counts. We will be filling the gap in our monitoring which resulted in this lengthy delay in availability of download metrics.

The timeline for the resolution of this issue is located here: https://status.npmjs.org/incidents/l3tx8t5mfmcs

**Comment by christian-bromann** [comment]
Thanks @joeledwards
